### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by petrnohejl** [ihardanilchanka/weather-android#1]
```
04-14 18:09:36.888: E/AndroidRuntime(29116): FATAL EXCEPTION: main
04-14 18:09:36.888: E/AndroidRuntime(29116): Process: by.ihar.weather.android, PID: 29116
04-14 18:09:36.888: E/AndroidRuntime(29116): java.lang.IllegalArgumentException: Target must not be null.
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at com.squareup.picasso.RequestCreator.into(RequestCreator.java:618)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at com.squareup.picasso.RequestCreator.into(RequestCreator.java:601)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at by.ihar.weather.android.fragment.TodayWeatherFragment.refreshTodayWeather(TodayWeatherFragment.java:136)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at by.ihar.weather.android.fragment.TodayWeatherFragment.access$000(TodayWeatherFragment.java:33)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at by.ihar.weather.android.fragment.TodayWeatherFragment$1.success(TodayWeatherFragment.java:94)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at by.ihar.weather.android.fragment.TodayWeatherFragment$1.success(TodayWeatherFragment.java:89)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at android.os.Handler.handleCallback(Handler.java:739)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at android.os.Looper.loop(Looper.java:135)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at java.lang.reflect.Method.invoke(Native Method)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
04-14 18:09:36.888: E/AndroidRuntime(29116): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ihardanilchanka** [comment]
Jsem ted v tescu, ale tipnul bych, ze picasso se snazi nacpat obrazek
drive, nez layout byl vytvoren. Doma to opravim. Docela by bylo uzitecne
rici ve ktery okamzik to spadlo :-)
Ihar

вт, 14 апр. 2015, 18:11, Petr Nohejl <notifications@github.com>:

**Comment by ihardanilchanka** [comment]
Nedalo se mi poradne nasimulovat tuto chybu, zkousel jsem na dvou zarizenich. Pro jistotu veskerou upravu layoutu fragmentu provadim in safe state, t.j. kdyz view a activity neni null.
